# Generated by Django 5.2.11 on 2026-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
