# Generated by Django 5.2.11 on 2026-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
    ]
